# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


  lane :match_read do
    match(type: "adhoc",
	  readonly: true
  )

  match(type: "development",
	  readonly: true
  )
  end

  lane :match_force do
 
  match(type: "adhoc",
	force: true
  )

  match(type: "development",
	force: true
  )
   
  end

lane :build_hockey do
  increment_build_number

   match(type: "adhoc",
    readonly: true
  )

  gym(scheme: "TestFastlane",
      clean: true,
      export_options: {
         method: "ad-hoc",
      }
  )
  
  hockey(
    api_token: "b061573721f54ba6b585b23980d47633", 
  )

end


